//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.XmlLegacyProvisioning {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XmlLegacyProvisioning.IServDataDirect")]
    public interface IServDataDirect {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServDataDirect/ServData", ReplyAction="http://tempuri.org/IServDataDirect/ServDataResponse")]
        System.IO.Stream ServData(System.IO.Stream inData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServDataDirect/ServData", ReplyAction="http://tempuri.org/IServDataDirect/ServDataResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> ServDataAsync(System.IO.Stream inData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServDataDirectChannel : Common.XmlLegacyProvisioning.IServDataDirect, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServDataDirectClient : System.ServiceModel.ClientBase<Common.XmlLegacyProvisioning.IServDataDirect>, Common.XmlLegacyProvisioning.IServDataDirect {
        
        public ServDataDirectClient() {
        }
        
        public ServDataDirectClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServDataDirectClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServDataDirectClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServDataDirectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream ServData(System.IO.Stream inData) {
            return base.Channel.ServData(inData);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> ServDataAsync(System.IO.Stream inData) {
            return base.Channel.ServDataAsync(inData);
        }
    }
}
