//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.UniveralCallManagementV3 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniversalCallMgrSubType", Namespace="http://schemas.datacontract.org/2004/07/UniveralCallManagementV3")]
    [System.SerializableAttribute()]
    public partial class UniversalCallMgrSubType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AnnouncementDelayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ForwardToVoicemailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.UniveralCallManagementV3.UniversalCallMgrItemType[] NumbersToCallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> TCMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> UseReleaseLinkTrunkingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AnnouncementDelay {
            get {
                return this.AnnouncementDelayField;
            }
            set {
                if ((this.AnnouncementDelayField.Equals(value) != true)) {
                    this.AnnouncementDelayField = value;
                    this.RaisePropertyChanged("AnnouncementDelay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Enabled {
            get {
                return this.EnabledField;
            }
            set {
                if ((this.EnabledField.Equals(value) != true)) {
                    this.EnabledField = value;
                    this.RaisePropertyChanged("Enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ForwardToVoicemail {
            get {
                return this.ForwardToVoicemailField;
            }
            set {
                if ((this.ForwardToVoicemailField.Equals(value) != true)) {
                    this.ForwardToVoicemailField = value;
                    this.RaisePropertyChanged("ForwardToVoicemail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.UniveralCallManagementV3.UniversalCallMgrItemType[] NumbersToCall {
            get {
                return this.NumbersToCallField;
            }
            set {
                if ((object.ReferenceEquals(this.NumbersToCallField, value) != true)) {
                    this.NumbersToCallField = value;
                    this.RaisePropertyChanged("NumbersToCall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberID {
            get {
                return this.SubscriberIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberIDField, value) != true)) {
                    this.SubscriberIDField = value;
                    this.RaisePropertyChanged("SubscriberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> TCM {
            get {
                return this.TCMField;
            }
            set {
                if ((this.TCMField.Equals(value) != true)) {
                    this.TCMField = value;
                    this.RaisePropertyChanged("TCM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> UseReleaseLinkTrunking {
            get {
                return this.UseReleaseLinkTrunkingField;
            }
            set {
                if ((this.UseReleaseLinkTrunkingField.Equals(value) != true)) {
                    this.UseReleaseLinkTrunkingField = value;
                    this.RaisePropertyChanged("UseReleaseLinkTrunking");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniversalCallMgrItemType", Namespace="http://schemas.datacontract.org/2004/07/UniveralCallManagementV3")]
    [System.SerializableAttribute()]
    public partial class UniversalCallMgrItemType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DelayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.UniveralCallManagementV3.ScheduleType[] ScheduleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.UniveralCallManagementV3.TransferNumber_e TransferNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.UniveralCallManagementV3.ContactListType[] VIPListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VerifyCalledPartyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WaitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Delay {
            get {
                return this.DelayField;
            }
            set {
                if ((this.DelayField.Equals(value) != true)) {
                    this.DelayField = value;
                    this.RaisePropertyChanged("Delay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enabled {
            get {
                return this.EnabledField;
            }
            set {
                if ((this.EnabledField.Equals(value) != true)) {
                    this.EnabledField = value;
                    this.RaisePropertyChanged("Enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.UniveralCallManagementV3.ScheduleType[] Schedule {
            get {
                return this.ScheduleField;
            }
            set {
                if ((object.ReferenceEquals(this.ScheduleField, value) != true)) {
                    this.ScheduleField = value;
                    this.RaisePropertyChanged("Schedule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.UniveralCallManagementV3.TransferNumber_e TransferNumber {
            get {
                return this.TransferNumberField;
            }
            set {
                if ((this.TransferNumberField.Equals(value) != true)) {
                    this.TransferNumberField = value;
                    this.RaisePropertyChanged("TransferNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.UniveralCallManagementV3.ContactListType[] VIPList {
            get {
                return this.VIPListField;
            }
            set {
                if ((object.ReferenceEquals(this.VIPListField, value) != true)) {
                    this.VIPListField = value;
                    this.RaisePropertyChanged("VIPList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VerifyCalledParty {
            get {
                return this.VerifyCalledPartyField;
            }
            set {
                if ((this.VerifyCalledPartyField.Equals(value) != true)) {
                    this.VerifyCalledPartyField = value;
                    this.RaisePropertyChanged("VerifyCalledParty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wait {
            get {
                return this.WaitField;
            }
            set {
                if ((this.WaitField.Equals(value) != true)) {
                    this.WaitField = value;
                    this.RaisePropertyChanged("Wait");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduleType", Namespace="http://schemas.datacontract.org/2004/07/UniveralCallManagementV3")]
    [System.SerializableAttribute()]
    public partial class ScheduleType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.UniveralCallManagementV3.DaysOfTheWeek_e DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.UniveralCallManagementV3.ScheduleType_e ScheduleTimeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.UniveralCallManagementV3.DaysOfTheWeek_e Day {
            get {
                return this.DayField;
            }
            set {
                if ((this.DayField.Equals(value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.UniveralCallManagementV3.ScheduleType_e ScheduleTimeType {
            get {
                return this.ScheduleTimeTypeField;
            }
            set {
                if ((this.ScheduleTimeTypeField.Equals(value) != true)) {
                    this.ScheduleTimeTypeField = value;
                    this.RaisePropertyChanged("ScheduleTimeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferNumber_e", Namespace="http://schemas.datacontract.org/2004/07/UniveralCallManagementV3")]
    public enum TransferNumber_e : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        One = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Two = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Three = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Four = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Five = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Six = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Seven = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Eight = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nine = 9,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactListType", Namespace="http://schemas.datacontract.org/2004/07/UniveralCallManagementV3")]
    [System.SerializableAttribute()]
    public partial class ContactListType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.UniveralCallManagementV3.VipType_e ContactTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactGuid {
            get {
                return this.ContactGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactGuidField, value) != true)) {
                    this.ContactGuidField = value;
                    this.RaisePropertyChanged("ContactGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName {
            get {
                return this.ContactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNameField, value) != true)) {
                    this.ContactNameField = value;
                    this.RaisePropertyChanged("ContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.UniveralCallManagementV3.VipType_e ContactType {
            get {
                return this.ContactTypeField;
            }
            set {
                if ((this.ContactTypeField.Equals(value) != true)) {
                    this.ContactTypeField = value;
                    this.RaisePropertyChanged("ContactType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DaysOfTheWeek_e", Namespace="http://schemas.datacontract.org/2004/07/UniveralCallManagementV3")]
    public enum DaysOfTheWeek_e : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sunday = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Monday = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tuesday = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wednesday = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Thursday = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friday = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Saturday = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduleType_e", Namespace="http://schemas.datacontract.org/2004/07/UniveralCallManagementV3")]
    public enum ScheduleType_e : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActiveAllDay = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InactiveAllDay = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Custom = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VipType_e", Namespace="http://schemas.datacontract.org/2004/07/UniveralCallManagementV3")]
    public enum VipType_e : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Group = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contact = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriberType", Namespace="http://schemas.datacontract.org/2004/07/APmaxProvisioning")]
    [System.SerializableAttribute()]
    public partial class SubscriberType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.UniveralCallManagementV3.AddressInfoType[] AddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingEnvironmentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingServiceAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DialByNameDigitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.UniveralCallManagementV3.InternetAccessType InternetAccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastUpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastUpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentSubscriberIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.UniveralCallManagementV3.PlacementType_e PlacementTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.UniveralCallManagementV3.ServiceInfoType ServiceInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberDefaultPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.UniveralCallManagementV3.Timezone_e SubscriberTimezoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.UniveralCallManagementV3.AddressInfoType[] Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingAccountNumber {
            get {
                return this.BillingAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingAccountNumberField, value) != true)) {
                    this.BillingAccountNumberField = value;
                    this.RaisePropertyChanged("BillingAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingEnvironmentCode {
            get {
                return this.BillingEnvironmentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingEnvironmentCodeField, value) != true)) {
                    this.BillingEnvironmentCodeField = value;
                    this.RaisePropertyChanged("BillingEnvironmentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingServiceAddress {
            get {
                return this.BillingServiceAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingServiceAddressField, value) != true)) {
                    this.BillingServiceAddressField = value;
                    this.RaisePropertyChanged("BillingServiceAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DialByNameDigits {
            get {
                return this.DialByNameDigitsField;
            }
            set {
                if ((object.ReferenceEquals(this.DialByNameDigitsField, value) != true)) {
                    this.DialByNameDigitsField = value;
                    this.RaisePropertyChanged("DialByNameDigits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.UniveralCallManagementV3.InternetAccessType InternetAccess {
            get {
                return this.InternetAccessField;
            }
            set {
                if ((object.ReferenceEquals(this.InternetAccessField, value) != true)) {
                    this.InternetAccessField = value;
                    this.RaisePropertyChanged("InternetAccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdateTime {
            get {
                return this.LastUpdateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.LastUpdateTimeField, value) != true)) {
                    this.LastUpdateTimeField = value;
                    this.RaisePropertyChanged("LastUpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdatedBy {
            get {
                return this.LastUpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastUpdatedByField, value) != true)) {
                    this.LastUpdatedByField = value;
                    this.RaisePropertyChanged("LastUpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentSubscriberId {
            get {
                return this.ParentSubscriberIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentSubscriberIdField, value) != true)) {
                    this.ParentSubscriberIdField = value;
                    this.RaisePropertyChanged("ParentSubscriberId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.UniveralCallManagementV3.PlacementType_e PlacementType {
            get {
                return this.PlacementTypeField;
            }
            set {
                if ((this.PlacementTypeField.Equals(value) != true)) {
                    this.PlacementTypeField = value;
                    this.RaisePropertyChanged("PlacementType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.UniveralCallManagementV3.ServiceInfoType ServiceInformation {
            get {
                return this.ServiceInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceInformationField, value) != true)) {
                    this.ServiceInformationField = value;
                    this.RaisePropertyChanged("ServiceInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberDefaultPhoneNumber {
            get {
                return this.SubscriberDefaultPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberDefaultPhoneNumberField, value) != true)) {
                    this.SubscriberDefaultPhoneNumberField = value;
                    this.RaisePropertyChanged("SubscriberDefaultPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberEmail {
            get {
                return this.SubscriberEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberEmailField, value) != true)) {
                    this.SubscriberEmailField = value;
                    this.RaisePropertyChanged("SubscriberEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberGuid {
            get {
                return this.SubscriberGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberGuidField, value) != true)) {
                    this.SubscriberGuidField = value;
                    this.RaisePropertyChanged("SubscriberGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberName {
            get {
                return this.SubscriberNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberNameField, value) != true)) {
                    this.SubscriberNameField = value;
                    this.RaisePropertyChanged("SubscriberName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.UniveralCallManagementV3.Timezone_e SubscriberTimezone {
            get {
                return this.SubscriberTimezoneField;
            }
            set {
                if ((this.SubscriberTimezoneField.Equals(value) != true)) {
                    this.SubscriberTimezoneField = value;
                    this.RaisePropertyChanged("SubscriberTimezone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternetAccessType", Namespace="http://schemas.datacontract.org/2004/07/APmaxProvisioning")]
    [System.SerializableAttribute()]
    public partial class InternetAccessType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MobileEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ServiceEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MobileEnabled {
            get {
                return this.MobileEnabledField;
            }
            set {
                if ((this.MobileEnabledField.Equals(value) != true)) {
                    this.MobileEnabledField = value;
                    this.RaisePropertyChanged("MobileEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ServiceEnabled {
            get {
                return this.ServiceEnabledField;
            }
            set {
                if ((this.ServiceEnabledField.Equals(value) != true)) {
                    this.ServiceEnabledField = value;
                    this.RaisePropertyChanged("ServiceEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceInfoType", Namespace="http://schemas.datacontract.org/2004/07/APmaxProvisioning")]
    [System.SerializableAttribute()]
    public partial class ServiceInfoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApSystemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingServiceAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingServiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.UniveralCallManagementV3.ServiceType_e ServiceTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApSystemId {
            get {
                return this.ApSystemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ApSystemIdField, value) != true)) {
                    this.ApSystemIdField = value;
                    this.RaisePropertyChanged("ApSystemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingServiceAddress {
            get {
                return this.BillingServiceAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingServiceAddressField, value) != true)) {
                    this.BillingServiceAddressField = value;
                    this.RaisePropertyChanged("BillingServiceAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingServiceID {
            get {
                return this.BillingServiceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingServiceIDField, value) != true)) {
                    this.BillingServiceIDField = value;
                    this.RaisePropertyChanged("BillingServiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceGuid {
            get {
                return this.ServiceGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceGuidField, value) != true)) {
                    this.ServiceGuidField = value;
                    this.RaisePropertyChanged("ServiceGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.UniveralCallManagementV3.ServiceType_e ServiceType {
            get {
                return this.ServiceTypeField;
            }
            set {
                if ((this.ServiceTypeField.Equals(value) != true)) {
                    this.ServiceTypeField = value;
                    this.RaisePropertyChanged("ServiceType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressInfoType", Namespace="http://schemas.datacontract.org/2004/07/APmaxProvisioning")]
    [System.SerializableAttribute()]
    public partial class AddressInfoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.UniveralCallManagementV3.AddressType_e AddressTypeFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressField {
            get {
                return this.AddressFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressFieldField, value) != true)) {
                    this.AddressFieldField = value;
                    this.RaisePropertyChanged("AddressField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.UniveralCallManagementV3.AddressType_e AddressTypeField {
            get {
                return this.AddressTypeFieldField;
            }
            set {
                if ((this.AddressTypeFieldField.Equals(value) != true)) {
                    this.AddressTypeFieldField = value;
                    this.RaisePropertyChanged("AddressTypeField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlacementType_e", Namespace="http://schemas.datacontract.org/2004/07/APmaxProvisioning")]
    public enum PlacementType_e : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlacementType_None = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlacementType_CASS = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlacementType_User = 10,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Timezone_e", Namespace="http://schemas.datacontract.org/2004/07/APmaxProvisioning")]
    public enum Timezone_e : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApDefault = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Midway = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hawaii = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alaska = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PacificTime = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Arizona = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MountainTime = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CentralTime = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Saskatchewan = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EasternTime = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IndianaEast = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AtlanticTime = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Newfoundland = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressType_e", Namespace="http://schemas.datacontract.org/2004/07/APmaxProvisioning")]
    public enum AddressType_e : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddressTypeDN = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddressTypeAnnID = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddressTypeEmailAddr = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddressTypeSipAddr = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddressTypMailboxNumber = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddressTypCentrexExtension = 15,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceType_e", Namespace="http://schemas.datacontract.org/2004/07/APmaxProvisioning")]
    public enum ServiceType_e : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Voicemail = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Iptv = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LargeScaleConferencing = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnDemandConferencing = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TerminatingCallManagement = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OriginatingCallManagement = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UniversalCallManagement = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CallLogging = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SipAcs = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WirelessOta = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACDAgent = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACDCallCenter = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SingleNumber = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notify = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SipIntercom = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IptvAluMmig = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IptvMediaroom = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoicemailMobile = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IptvMobile = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotifyMobile = 20,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UniveralCallManagementV3.IUCMService")]
    public interface IUCMService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUCMService/AddUniversalCallManagerSubscriber", ReplyAction="http://tempuri.org/IUCMService/AddUniversalCallManagerSubscriberResponse")]
        void AddUniversalCallManagerSubscriber(string loginToken, Common.UniveralCallManagementV3.UniversalCallMgrSubType ucmSub, Common.UniveralCallManagementV3.SubscriberType subscriber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUCMService/AddUniversalCallManagerSubscriber", ReplyAction="http://tempuri.org/IUCMService/AddUniversalCallManagerSubscriberResponse")]
        System.Threading.Tasks.Task AddUniversalCallManagerSubscriberAsync(string loginToken, Common.UniveralCallManagementV3.UniversalCallMgrSubType ucmSub, Common.UniveralCallManagementV3.SubscriberType subscriber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUCMService/UpdateUniversalCallManagerSubscriber", ReplyAction="http://tempuri.org/IUCMService/UpdateUniversalCallManagerSubscriberResponse")]
        void UpdateUniversalCallManagerSubscriber(string loginToken, Common.UniveralCallManagementV3.UniversalCallMgrSubType ucmSub, Common.UniveralCallManagementV3.InternetAccessType internetInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUCMService/UpdateUniversalCallManagerSubscriber", ReplyAction="http://tempuri.org/IUCMService/UpdateUniversalCallManagerSubscriberResponse")]
        System.Threading.Tasks.Task UpdateUniversalCallManagerSubscriberAsync(string loginToken, Common.UniveralCallManagementV3.UniversalCallMgrSubType ucmSub, Common.UniveralCallManagementV3.InternetAccessType internetInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUCMService/DeleteUniversalCallManagerSubscriber", ReplyAction="http://tempuri.org/IUCMService/DeleteUniversalCallManagerSubscriberResponse")]
        void DeleteUniversalCallManagerSubscriber(string loginToken, string subscriberAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUCMService/DeleteUniversalCallManagerSubscriber", ReplyAction="http://tempuri.org/IUCMService/DeleteUniversalCallManagerSubscriberResponse")]
        System.Threading.Tasks.Task DeleteUniversalCallManagerSubscriberAsync(string loginToken, string subscriberAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUCMService/GetUniversalCallManagerSubscriber", ReplyAction="http://tempuri.org/IUCMService/GetUniversalCallManagerSubscriberResponse")]
        Common.UniveralCallManagementV3.UniversalCallMgrSubType GetUniversalCallManagerSubscriber(string loginToken, string subscriberID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUCMService/GetUniversalCallManagerSubscriber", ReplyAction="http://tempuri.org/IUCMService/GetUniversalCallManagerSubscriberResponse")]
        System.Threading.Tasks.Task<Common.UniveralCallManagementV3.UniversalCallMgrSubType> GetUniversalCallManagerSubscriberAsync(string loginToken, string subscriberID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUCMService/GetUniversalCallManagerNumber", ReplyAction="http://tempuri.org/IUCMService/GetUniversalCallManagerNumberResponse")]
        Common.UniveralCallManagementV3.UniversalCallMgrSubType GetUniversalCallManagerNumber(string loginToken, string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUCMService/GetUniversalCallManagerNumber", ReplyAction="http://tempuri.org/IUCMService/GetUniversalCallManagerNumberResponse")]
        System.Threading.Tasks.Task<Common.UniveralCallManagementV3.UniversalCallMgrSubType> GetUniversalCallManagerNumberAsync(string loginToken, string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUCMService/GetUniversalCallManagerBilling", ReplyAction="http://tempuri.org/IUCMService/GetUniversalCallManagerBillingResponse")]
        Common.UniveralCallManagementV3.UniversalCallMgrSubType GetUniversalCallManagerBilling(string loginToken, string billingNumber, string billingServiceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUCMService/GetUniversalCallManagerBilling", ReplyAction="http://tempuri.org/IUCMService/GetUniversalCallManagerBillingResponse")]
        System.Threading.Tasks.Task<Common.UniveralCallManagementV3.UniversalCallMgrSubType> GetUniversalCallManagerBillingAsync(string loginToken, string billingNumber, string billingServiceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUCMService/GetSubscribersContacts", ReplyAction="http://tempuri.org/IUCMService/GetSubscribersContactsResponse")]
        Common.UniveralCallManagementV3.ContactListType[] GetSubscribersContacts(string loginToken, string subscriberAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUCMService/GetSubscribersContacts", ReplyAction="http://tempuri.org/IUCMService/GetSubscribersContactsResponse")]
        System.Threading.Tasks.Task<Common.UniveralCallManagementV3.ContactListType[]> GetSubscribersContactsAsync(string loginToken, string subscriberAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUCMServiceChannel : Common.UniveralCallManagementV3.IUCMService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UCMServiceClient : System.ServiceModel.ClientBase<Common.UniveralCallManagementV3.IUCMService>, Common.UniveralCallManagementV3.IUCMService {
        
        public UCMServiceClient() {
        }
        
        public UCMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UCMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UCMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UCMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddUniversalCallManagerSubscriber(string loginToken, Common.UniveralCallManagementV3.UniversalCallMgrSubType ucmSub, Common.UniveralCallManagementV3.SubscriberType subscriber) {
            base.Channel.AddUniversalCallManagerSubscriber(loginToken, ucmSub, subscriber);
        }
        
        public System.Threading.Tasks.Task AddUniversalCallManagerSubscriberAsync(string loginToken, Common.UniveralCallManagementV3.UniversalCallMgrSubType ucmSub, Common.UniveralCallManagementV3.SubscriberType subscriber) {
            return base.Channel.AddUniversalCallManagerSubscriberAsync(loginToken, ucmSub, subscriber);
        }
        
        public void UpdateUniversalCallManagerSubscriber(string loginToken, Common.UniveralCallManagementV3.UniversalCallMgrSubType ucmSub, Common.UniveralCallManagementV3.InternetAccessType internetInfo) {
            base.Channel.UpdateUniversalCallManagerSubscriber(loginToken, ucmSub, internetInfo);
        }
        
        public System.Threading.Tasks.Task UpdateUniversalCallManagerSubscriberAsync(string loginToken, Common.UniveralCallManagementV3.UniversalCallMgrSubType ucmSub, Common.UniveralCallManagementV3.InternetAccessType internetInfo) {
            return base.Channel.UpdateUniversalCallManagerSubscriberAsync(loginToken, ucmSub, internetInfo);
        }
        
        public void DeleteUniversalCallManagerSubscriber(string loginToken, string subscriberAddress) {
            base.Channel.DeleteUniversalCallManagerSubscriber(loginToken, subscriberAddress);
        }
        
        public System.Threading.Tasks.Task DeleteUniversalCallManagerSubscriberAsync(string loginToken, string subscriberAddress) {
            return base.Channel.DeleteUniversalCallManagerSubscriberAsync(loginToken, subscriberAddress);
        }
        
        public Common.UniveralCallManagementV3.UniversalCallMgrSubType GetUniversalCallManagerSubscriber(string loginToken, string subscriberID) {
            return base.Channel.GetUniversalCallManagerSubscriber(loginToken, subscriberID);
        }
        
        public System.Threading.Tasks.Task<Common.UniveralCallManagementV3.UniversalCallMgrSubType> GetUniversalCallManagerSubscriberAsync(string loginToken, string subscriberID) {
            return base.Channel.GetUniversalCallManagerSubscriberAsync(loginToken, subscriberID);
        }
        
        public Common.UniveralCallManagementV3.UniversalCallMgrSubType GetUniversalCallManagerNumber(string loginToken, string phoneNumber) {
            return base.Channel.GetUniversalCallManagerNumber(loginToken, phoneNumber);
        }
        
        public System.Threading.Tasks.Task<Common.UniveralCallManagementV3.UniversalCallMgrSubType> GetUniversalCallManagerNumberAsync(string loginToken, string phoneNumber) {
            return base.Channel.GetUniversalCallManagerNumberAsync(loginToken, phoneNumber);
        }
        
        public Common.UniveralCallManagementV3.UniversalCallMgrSubType GetUniversalCallManagerBilling(string loginToken, string billingNumber, string billingServiceID) {
            return base.Channel.GetUniversalCallManagerBilling(loginToken, billingNumber, billingServiceID);
        }
        
        public System.Threading.Tasks.Task<Common.UniveralCallManagementV3.UniversalCallMgrSubType> GetUniversalCallManagerBillingAsync(string loginToken, string billingNumber, string billingServiceID) {
            return base.Channel.GetUniversalCallManagerBillingAsync(loginToken, billingNumber, billingServiceID);
        }
        
        public Common.UniveralCallManagementV3.ContactListType[] GetSubscribersContacts(string loginToken, string subscriberAddress) {
            return base.Channel.GetSubscribersContacts(loginToken, subscriberAddress);
        }
        
        public System.Threading.Tasks.Task<Common.UniveralCallManagementV3.ContactListType[]> GetSubscribersContactsAsync(string loginToken, string subscriberAddress) {
            return base.Channel.GetSubscribersContactsAsync(loginToken, subscriberAddress);
        }
    }
}
