//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.TerminatingCallManagementV3 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCMType", Namespace="http://schemas.datacontract.org/2004/07/TerminatingCallManagementV3")]
    [System.SerializableAttribute()]
    public partial class TCMType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> AllowDistinctiveRingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.TerminatingCallManagementV3.TCMCallListType[] AllowedListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AnnouncementHitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BlockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.TerminatingCallManagementV3.TCMCallListType[] BlockedListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.TerminatingCallManagementV3.DNDContactListType[] ContactListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DialthruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DisconnectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DndCallsBlockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DndFeatureEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DndManagementEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DndPinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DndPinCollectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.TerminatingCallManagementV3.DNDScheduleType[] DndScheduleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DndSubscriberEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Common.TerminatingCallManagementV3.TimeoutAction> DndTimeoutTreatmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ForwardToVmCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastAccessedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastCallingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastUploadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxAllowedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxBlockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxFriendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Common.TerminatingCallManagementV3.CallerActions> PrivateCallerTreatmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Common.TerminatingCallManagementV3.Language> SubLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberDnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> TcmFeatureEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> TcmManagementEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> TcmSubscriberEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Common.TerminatingCallManagementV3.TimeoutAction> TcmTimeoutTreatmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Common.TerminatingCallManagementV3.CallerActions> UnknownNumberTreatmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VmAdminNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> AllowDistinctiveRing {
            get {
                return this.AllowDistinctiveRingField;
            }
            set {
                if ((this.AllowDistinctiveRingField.Equals(value) != true)) {
                    this.AllowDistinctiveRingField = value;
                    this.RaisePropertyChanged("AllowDistinctiveRing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.TerminatingCallManagementV3.TCMCallListType[] AllowedList {
            get {
                return this.AllowedListField;
            }
            set {
                if ((object.ReferenceEquals(this.AllowedListField, value) != true)) {
                    this.AllowedListField = value;
                    this.RaisePropertyChanged("AllowedList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AnnouncementHit {
            get {
                return this.AnnouncementHitField;
            }
            set {
                if ((this.AnnouncementHitField.Equals(value) != true)) {
                    this.AnnouncementHitField = value;
                    this.RaisePropertyChanged("AnnouncementHit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Blocked {
            get {
                return this.BlockedField;
            }
            set {
                if ((this.BlockedField.Equals(value) != true)) {
                    this.BlockedField = value;
                    this.RaisePropertyChanged("Blocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.TerminatingCallManagementV3.TCMCallListType[] BlockedList {
            get {
                return this.BlockedListField;
            }
            set {
                if ((object.ReferenceEquals(this.BlockedListField, value) != true)) {
                    this.BlockedListField = value;
                    this.RaisePropertyChanged("BlockedList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.TerminatingCallManagementV3.DNDContactListType[] ContactList {
            get {
                return this.ContactListField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactListField, value) != true)) {
                    this.ContactListField = value;
                    this.RaisePropertyChanged("ContactList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Dialthru {
            get {
                return this.DialthruField;
            }
            set {
                if ((this.DialthruField.Equals(value) != true)) {
                    this.DialthruField = value;
                    this.RaisePropertyChanged("Dialthru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Disconnect {
            get {
                return this.DisconnectField;
            }
            set {
                if ((this.DisconnectField.Equals(value) != true)) {
                    this.DisconnectField = value;
                    this.RaisePropertyChanged("Disconnect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DndCallsBlocked {
            get {
                return this.DndCallsBlockedField;
            }
            set {
                if ((this.DndCallsBlockedField.Equals(value) != true)) {
                    this.DndCallsBlockedField = value;
                    this.RaisePropertyChanged("DndCallsBlocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DndFeatureEnabled {
            get {
                return this.DndFeatureEnabledField;
            }
            set {
                if ((this.DndFeatureEnabledField.Equals(value) != true)) {
                    this.DndFeatureEnabledField = value;
                    this.RaisePropertyChanged("DndFeatureEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DndManagementEnabled {
            get {
                return this.DndManagementEnabledField;
            }
            set {
                if ((this.DndManagementEnabledField.Equals(value) != true)) {
                    this.DndManagementEnabledField = value;
                    this.RaisePropertyChanged("DndManagementEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DndPin {
            get {
                return this.DndPinField;
            }
            set {
                if ((object.ReferenceEquals(this.DndPinField, value) != true)) {
                    this.DndPinField = value;
                    this.RaisePropertyChanged("DndPin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DndPinCollected {
            get {
                return this.DndPinCollectedField;
            }
            set {
                if ((this.DndPinCollectedField.Equals(value) != true)) {
                    this.DndPinCollectedField = value;
                    this.RaisePropertyChanged("DndPinCollected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.TerminatingCallManagementV3.DNDScheduleType[] DndSchedule {
            get {
                return this.DndScheduleField;
            }
            set {
                if ((object.ReferenceEquals(this.DndScheduleField, value) != true)) {
                    this.DndScheduleField = value;
                    this.RaisePropertyChanged("DndSchedule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DndSubscriberEnabled {
            get {
                return this.DndSubscriberEnabledField;
            }
            set {
                if ((this.DndSubscriberEnabledField.Equals(value) != true)) {
                    this.DndSubscriberEnabledField = value;
                    this.RaisePropertyChanged("DndSubscriberEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Common.TerminatingCallManagementV3.TimeoutAction> DndTimeoutTreatment {
            get {
                return this.DndTimeoutTreatmentField;
            }
            set {
                if ((this.DndTimeoutTreatmentField.Equals(value) != true)) {
                    this.DndTimeoutTreatmentField = value;
                    this.RaisePropertyChanged("DndTimeoutTreatment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ForwardToVmCount {
            get {
                return this.ForwardToVmCountField;
            }
            set {
                if ((this.ForwardToVmCountField.Equals(value) != true)) {
                    this.ForwardToVmCountField = value;
                    this.RaisePropertyChanged("ForwardToVmCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastAccessed {
            get {
                return this.LastAccessedField;
            }
            set {
                if ((object.ReferenceEquals(this.LastAccessedField, value) != true)) {
                    this.LastAccessedField = value;
                    this.RaisePropertyChanged("LastAccessed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastCallingNumber {
            get {
                return this.LastCallingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.LastCallingNumberField, value) != true)) {
                    this.LastCallingNumberField = value;
                    this.RaisePropertyChanged("LastCallingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpload {
            get {
                return this.LastUploadField;
            }
            set {
                if ((object.ReferenceEquals(this.LastUploadField, value) != true)) {
                    this.LastUploadField = value;
                    this.RaisePropertyChanged("LastUpload");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxAllowed {
            get {
                return this.MaxAllowedField;
            }
            set {
                if ((this.MaxAllowedField.Equals(value) != true)) {
                    this.MaxAllowedField = value;
                    this.RaisePropertyChanged("MaxAllowed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxBlocked {
            get {
                return this.MaxBlockedField;
            }
            set {
                if ((this.MaxBlockedField.Equals(value) != true)) {
                    this.MaxBlockedField = value;
                    this.RaisePropertyChanged("MaxBlocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxFriends {
            get {
                return this.MaxFriendsField;
            }
            set {
                if ((this.MaxFriendsField.Equals(value) != true)) {
                    this.MaxFriendsField = value;
                    this.RaisePropertyChanged("MaxFriends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Common.TerminatingCallManagementV3.CallerActions> PrivateCallerTreatment {
            get {
                return this.PrivateCallerTreatmentField;
            }
            set {
                if ((this.PrivateCallerTreatmentField.Equals(value) != true)) {
                    this.PrivateCallerTreatmentField = value;
                    this.RaisePropertyChanged("PrivateCallerTreatment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Common.TerminatingCallManagementV3.Language> SubLanguage {
            get {
                return this.SubLanguageField;
            }
            set {
                if ((this.SubLanguageField.Equals(value) != true)) {
                    this.SubLanguageField = value;
                    this.RaisePropertyChanged("SubLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberDn {
            get {
                return this.SubscriberDnField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberDnField, value) != true)) {
                    this.SubscriberDnField = value;
                    this.RaisePropertyChanged("SubscriberDn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberGuid {
            get {
                return this.SubscriberGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberGuidField, value) != true)) {
                    this.SubscriberGuidField = value;
                    this.RaisePropertyChanged("SubscriberGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> TcmFeatureEnabled {
            get {
                return this.TcmFeatureEnabledField;
            }
            set {
                if ((this.TcmFeatureEnabledField.Equals(value) != true)) {
                    this.TcmFeatureEnabledField = value;
                    this.RaisePropertyChanged("TcmFeatureEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> TcmManagementEnabled {
            get {
                return this.TcmManagementEnabledField;
            }
            set {
                if ((this.TcmManagementEnabledField.Equals(value) != true)) {
                    this.TcmManagementEnabledField = value;
                    this.RaisePropertyChanged("TcmManagementEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> TcmSubscriberEnabled {
            get {
                return this.TcmSubscriberEnabledField;
            }
            set {
                if ((this.TcmSubscriberEnabledField.Equals(value) != true)) {
                    this.TcmSubscriberEnabledField = value;
                    this.RaisePropertyChanged("TcmSubscriberEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Common.TerminatingCallManagementV3.TimeoutAction> TcmTimeoutTreatment {
            get {
                return this.TcmTimeoutTreatmentField;
            }
            set {
                if ((this.TcmTimeoutTreatmentField.Equals(value) != true)) {
                    this.TcmTimeoutTreatmentField = value;
                    this.RaisePropertyChanged("TcmTimeoutTreatment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeZone {
            get {
                return this.TimeZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeZoneField, value) != true)) {
                    this.TimeZoneField = value;
                    this.RaisePropertyChanged("TimeZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Common.TerminatingCallManagementV3.CallerActions> UnknownNumberTreatment {
            get {
                return this.UnknownNumberTreatmentField;
            }
            set {
                if ((this.UnknownNumberTreatmentField.Equals(value) != true)) {
                    this.UnknownNumberTreatmentField = value;
                    this.RaisePropertyChanged("UnknownNumberTreatment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VmAdminNumber {
            get {
                return this.VmAdminNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.VmAdminNumberField, value) != true)) {
                    this.VmAdminNumberField = value;
                    this.RaisePropertyChanged("VmAdminNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCMCallListType", Namespace="http://schemas.datacontract.org/2004/07/TerminatingCallManagementV3")]
    [System.SerializableAttribute()]
    public partial class TCMCallListType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Common.TerminatingCallManagementV3.AddDelete> AddOrDeleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnduringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastCallDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumCallsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Common.TerminatingCallManagementV3.AddDelete> AddOrDelete {
            get {
                return this.AddOrDeleteField;
            }
            set {
                if ((this.AddOrDeleteField.Equals(value) != true)) {
                    this.AddOrDeleteField = value;
                    this.RaisePropertyChanged("AddOrDelete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dn {
            get {
                return this.DnField;
            }
            set {
                if ((object.ReferenceEquals(this.DnField, value) != true)) {
                    this.DnField = value;
                    this.RaisePropertyChanged("Dn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enduring {
            get {
                return this.EnduringField;
            }
            set {
                if ((this.EnduringField.Equals(value) != true)) {
                    this.EnduringField = value;
                    this.RaisePropertyChanged("Enduring");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastCallDate {
            get {
                return this.LastCallDateField;
            }
            set {
                if ((object.ReferenceEquals(this.LastCallDateField, value) != true)) {
                    this.LastCallDateField = value;
                    this.RaisePropertyChanged("LastCallDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumCalls {
            get {
                return this.NumCallsField;
            }
            set {
                if ((this.NumCallsField.Equals(value) != true)) {
                    this.NumCallsField = value;
                    this.RaisePropertyChanged("NumCalls");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DNDContactListType", Namespace="http://schemas.datacontract.org/2004/07/TerminatingCallManagementV3")]
    [System.SerializableAttribute()]
    public partial class DNDContactListType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Common.TerminatingCallManagementV3.AddDelete> AddOrDeleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.TerminatingCallManagementV3.ContactType ContactTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Common.TerminatingCallManagementV3.AddDelete> AddOrDelete {
            get {
                return this.AddOrDeleteField;
            }
            set {
                if ((this.AddOrDeleteField.Equals(value) != true)) {
                    this.AddOrDeleteField = value;
                    this.RaisePropertyChanged("AddOrDelete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactGuid {
            get {
                return this.ContactGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactGuidField, value) != true)) {
                    this.ContactGuidField = value;
                    this.RaisePropertyChanged("ContactGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName {
            get {
                return this.ContactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNameField, value) != true)) {
                    this.ContactNameField = value;
                    this.RaisePropertyChanged("ContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.TerminatingCallManagementV3.ContactType ContactType {
            get {
                return this.ContactTypeField;
            }
            set {
                if ((this.ContactTypeField.Equals(value) != true)) {
                    this.ContactTypeField = value;
                    this.RaisePropertyChanged("ContactType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DNDScheduleType", Namespace="http://schemas.datacontract.org/2004/07/TerminatingCallManagementV3")]
    [System.SerializableAttribute()]
    public partial class DNDScheduleType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Day {
            get {
                return this.DayField;
            }
            set {
                if ((this.DayField.Equals(value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EndTimeField, value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartTimeField, value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeoutAction", Namespace="http://schemas.datacontract.org/2004/07/TerminatingCallManagementV3")]
    public enum TimeoutAction : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Allowed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Forward = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallerActions", Namespace="http://schemas.datacontract.org/2004/07/TerminatingCallManagementV3")]
    public enum CallerActions : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Allowed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Challenged = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Forward = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://schemas.datacontract.org/2004/07/TerminatingCallManagementV3")]
    public enum Language : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        English = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spanish = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddDelete", Namespace="http://schemas.datacontract.org/2004/07/TerminatingCallManagementV3")]
    public enum AddDelete : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Add = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactType", Namespace="http://schemas.datacontract.org/2004/07/TerminatingCallManagementV3")]
    public enum ContactType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Group = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friend = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriberType", Namespace="http://schemas.datacontract.org/2004/07/APmaxProvisioning")]
    [System.SerializableAttribute()]
    public partial class SubscriberType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.TerminatingCallManagementV3.AddressInfoType[] AddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingEnvironmentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingServiceAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DialByNameDigitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.TerminatingCallManagementV3.InternetAccessType InternetAccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastUpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastUpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentSubscriberIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.TerminatingCallManagementV3.PlacementType_e PlacementTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.TerminatingCallManagementV3.ServiceInfoType ServiceInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberDefaultPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.TerminatingCallManagementV3.Timezone_e SubscriberTimezoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.TerminatingCallManagementV3.AddressInfoType[] Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingAccountNumber {
            get {
                return this.BillingAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingAccountNumberField, value) != true)) {
                    this.BillingAccountNumberField = value;
                    this.RaisePropertyChanged("BillingAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingEnvironmentCode {
            get {
                return this.BillingEnvironmentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingEnvironmentCodeField, value) != true)) {
                    this.BillingEnvironmentCodeField = value;
                    this.RaisePropertyChanged("BillingEnvironmentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingServiceAddress {
            get {
                return this.BillingServiceAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingServiceAddressField, value) != true)) {
                    this.BillingServiceAddressField = value;
                    this.RaisePropertyChanged("BillingServiceAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DialByNameDigits {
            get {
                return this.DialByNameDigitsField;
            }
            set {
                if ((object.ReferenceEquals(this.DialByNameDigitsField, value) != true)) {
                    this.DialByNameDigitsField = value;
                    this.RaisePropertyChanged("DialByNameDigits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.TerminatingCallManagementV3.InternetAccessType InternetAccess {
            get {
                return this.InternetAccessField;
            }
            set {
                if ((object.ReferenceEquals(this.InternetAccessField, value) != true)) {
                    this.InternetAccessField = value;
                    this.RaisePropertyChanged("InternetAccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdateTime {
            get {
                return this.LastUpdateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.LastUpdateTimeField, value) != true)) {
                    this.LastUpdateTimeField = value;
                    this.RaisePropertyChanged("LastUpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdatedBy {
            get {
                return this.LastUpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastUpdatedByField, value) != true)) {
                    this.LastUpdatedByField = value;
                    this.RaisePropertyChanged("LastUpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentSubscriberId {
            get {
                return this.ParentSubscriberIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentSubscriberIdField, value) != true)) {
                    this.ParentSubscriberIdField = value;
                    this.RaisePropertyChanged("ParentSubscriberId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.TerminatingCallManagementV3.PlacementType_e PlacementType {
            get {
                return this.PlacementTypeField;
            }
            set {
                if ((this.PlacementTypeField.Equals(value) != true)) {
                    this.PlacementTypeField = value;
                    this.RaisePropertyChanged("PlacementType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.TerminatingCallManagementV3.ServiceInfoType ServiceInformation {
            get {
                return this.ServiceInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceInformationField, value) != true)) {
                    this.ServiceInformationField = value;
                    this.RaisePropertyChanged("ServiceInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberDefaultPhoneNumber {
            get {
                return this.SubscriberDefaultPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberDefaultPhoneNumberField, value) != true)) {
                    this.SubscriberDefaultPhoneNumberField = value;
                    this.RaisePropertyChanged("SubscriberDefaultPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberEmail {
            get {
                return this.SubscriberEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberEmailField, value) != true)) {
                    this.SubscriberEmailField = value;
                    this.RaisePropertyChanged("SubscriberEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberGuid {
            get {
                return this.SubscriberGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberGuidField, value) != true)) {
                    this.SubscriberGuidField = value;
                    this.RaisePropertyChanged("SubscriberGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberName {
            get {
                return this.SubscriberNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberNameField, value) != true)) {
                    this.SubscriberNameField = value;
                    this.RaisePropertyChanged("SubscriberName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.TerminatingCallManagementV3.Timezone_e SubscriberTimezone {
            get {
                return this.SubscriberTimezoneField;
            }
            set {
                if ((this.SubscriberTimezoneField.Equals(value) != true)) {
                    this.SubscriberTimezoneField = value;
                    this.RaisePropertyChanged("SubscriberTimezone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternetAccessType", Namespace="http://schemas.datacontract.org/2004/07/APmaxProvisioning")]
    [System.SerializableAttribute()]
    public partial class InternetAccessType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MobileEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ServiceEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MobileEnabled {
            get {
                return this.MobileEnabledField;
            }
            set {
                if ((this.MobileEnabledField.Equals(value) != true)) {
                    this.MobileEnabledField = value;
                    this.RaisePropertyChanged("MobileEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ServiceEnabled {
            get {
                return this.ServiceEnabledField;
            }
            set {
                if ((this.ServiceEnabledField.Equals(value) != true)) {
                    this.ServiceEnabledField = value;
                    this.RaisePropertyChanged("ServiceEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceInfoType", Namespace="http://schemas.datacontract.org/2004/07/APmaxProvisioning")]
    [System.SerializableAttribute()]
    public partial class ServiceInfoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApSystemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingServiceAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingServiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.TerminatingCallManagementV3.ServiceType_e ServiceTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApSystemId {
            get {
                return this.ApSystemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ApSystemIdField, value) != true)) {
                    this.ApSystemIdField = value;
                    this.RaisePropertyChanged("ApSystemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingServiceAddress {
            get {
                return this.BillingServiceAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingServiceAddressField, value) != true)) {
                    this.BillingServiceAddressField = value;
                    this.RaisePropertyChanged("BillingServiceAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingServiceID {
            get {
                return this.BillingServiceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingServiceIDField, value) != true)) {
                    this.BillingServiceIDField = value;
                    this.RaisePropertyChanged("BillingServiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceGuid {
            get {
                return this.ServiceGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceGuidField, value) != true)) {
                    this.ServiceGuidField = value;
                    this.RaisePropertyChanged("ServiceGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.TerminatingCallManagementV3.ServiceType_e ServiceType {
            get {
                return this.ServiceTypeField;
            }
            set {
                if ((this.ServiceTypeField.Equals(value) != true)) {
                    this.ServiceTypeField = value;
                    this.RaisePropertyChanged("ServiceType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressInfoType", Namespace="http://schemas.datacontract.org/2004/07/APmaxProvisioning")]
    [System.SerializableAttribute()]
    public partial class AddressInfoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Common.TerminatingCallManagementV3.AddressType_e AddressTypeFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressField {
            get {
                return this.AddressFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressFieldField, value) != true)) {
                    this.AddressFieldField = value;
                    this.RaisePropertyChanged("AddressField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.TerminatingCallManagementV3.AddressType_e AddressTypeField {
            get {
                return this.AddressTypeFieldField;
            }
            set {
                if ((this.AddressTypeFieldField.Equals(value) != true)) {
                    this.AddressTypeFieldField = value;
                    this.RaisePropertyChanged("AddressTypeField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlacementType_e", Namespace="http://schemas.datacontract.org/2004/07/APmaxProvisioning")]
    public enum PlacementType_e : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlacementType_None = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlacementType_CASS = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlacementType_User = 10,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Timezone_e", Namespace="http://schemas.datacontract.org/2004/07/APmaxProvisioning")]
    public enum Timezone_e : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApDefault = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Midway = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hawaii = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alaska = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PacificTime = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Arizona = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MountainTime = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CentralTime = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Saskatchewan = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EasternTime = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IndianaEast = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AtlanticTime = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Newfoundland = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressType_e", Namespace="http://schemas.datacontract.org/2004/07/APmaxProvisioning")]
    public enum AddressType_e : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddressTypeDN = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddressTypeAnnID = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddressTypeEmailAddr = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddressTypeSipAddr = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddressTypMailboxNumber = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddressTypCentrexExtension = 15,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceType_e", Namespace="http://schemas.datacontract.org/2004/07/APmaxProvisioning")]
    public enum ServiceType_e : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Voicemail = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Iptv = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LargeScaleConferencing = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnDemandConferencing = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TerminatingCallManagement = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OriginatingCallManagement = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UniversalCallManagement = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CallLogging = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SipAcs = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WirelessOta = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACDAgent = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACDCallCenter = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SingleNumber = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notify = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SipIntercom = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IptvAluMmig = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IptvMediaroom = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoicemailMobile = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IptvMobile = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotifyMobile = 20,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TerminatingCallManagementV3.ITCMService")]
    public interface ITCMService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCMService/GetTCMSubscriber", ReplyAction="http://tempuri.org/ITCMService/GetTCMSubscriberResponse")]
        Common.TerminatingCallManagementV3.TCMType GetTCMSubscriber(string loginToken, string subscriberAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCMService/GetTCMSubscriber", ReplyAction="http://tempuri.org/ITCMService/GetTCMSubscriberResponse")]
        System.Threading.Tasks.Task<Common.TerminatingCallManagementV3.TCMType> GetTCMSubscriberAsync(string loginToken, string subscriberAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCMService/AddTCMSubscriber", ReplyAction="http://tempuri.org/ITCMService/AddTCMSubscriberResponse")]
        void AddTCMSubscriber(string loginToken, string subscriberAddress, bool tcmEnabled, bool dndEnabled, Common.TerminatingCallManagementV3.SubscriberType subscriber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCMService/AddTCMSubscriber", ReplyAction="http://tempuri.org/ITCMService/AddTCMSubscriberResponse")]
        System.Threading.Tasks.Task AddTCMSubscriberAsync(string loginToken, string subscriberAddress, bool tcmEnabled, bool dndEnabled, Common.TerminatingCallManagementV3.SubscriberType subscriber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCMService/UpdateTCMSubscriber", ReplyAction="http://tempuri.org/ITCMService/UpdateTCMSubscriberResponse")]
        void UpdateTCMSubscriber(string loginToken, Common.TerminatingCallManagementV3.TCMType tcmSub, Common.TerminatingCallManagementV3.InternetAccessType internetInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCMService/UpdateTCMSubscriber", ReplyAction="http://tempuri.org/ITCMService/UpdateTCMSubscriberResponse")]
        System.Threading.Tasks.Task UpdateTCMSubscriberAsync(string loginToken, Common.TerminatingCallManagementV3.TCMType tcmSub, Common.TerminatingCallManagementV3.InternetAccessType internetInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCMService/DeleteTCMSubscriber", ReplyAction="http://tempuri.org/ITCMService/DeleteTCMSubscriberResponse")]
        void DeleteTCMSubscriber(string loginToken, string subscriberAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCMService/DeleteTCMSubscriber", ReplyAction="http://tempuri.org/ITCMService/DeleteTCMSubscriberResponse")]
        System.Threading.Tasks.Task DeleteTCMSubscriberAsync(string loginToken, string subscriberAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCMService/TCMFeature", ReplyAction="http://tempuri.org/ITCMService/TCMFeatureResponse")]
        void TCMFeature(string loginToken, string subscriberAddress, bool enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCMService/TCMFeature", ReplyAction="http://tempuri.org/ITCMService/TCMFeatureResponse")]
        System.Threading.Tasks.Task TCMFeatureAsync(string loginToken, string subscriberAddress, bool enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCMService/DNDFeature", ReplyAction="http://tempuri.org/ITCMService/DNDFeatureResponse")]
        void DNDFeature(string loginToken, string subscriberAddress, bool enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCMService/DNDFeature", ReplyAction="http://tempuri.org/ITCMService/DNDFeatureResponse")]
        System.Threading.Tasks.Task DNDFeatureAsync(string loginToken, string subscriberAddress, bool enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCMService/GetSubscribersContacts", ReplyAction="http://tempuri.org/ITCMService/GetSubscribersContactsResponse")]
        Common.TerminatingCallManagementV3.DNDContactListType[] GetSubscribersContacts(string loginToken, string subscriberAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCMService/GetSubscribersContacts", ReplyAction="http://tempuri.org/ITCMService/GetSubscribersContactsResponse")]
        System.Threading.Tasks.Task<Common.TerminatingCallManagementV3.DNDContactListType[]> GetSubscribersContactsAsync(string loginToken, string subscriberAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITCMServiceChannel : Common.TerminatingCallManagementV3.ITCMService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TCMServiceClient : System.ServiceModel.ClientBase<Common.TerminatingCallManagementV3.ITCMService>, Common.TerminatingCallManagementV3.ITCMService {
        
        public TCMServiceClient() {
        }
        
        public TCMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TCMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Common.TerminatingCallManagementV3.TCMType GetTCMSubscriber(string loginToken, string subscriberAddress) {
            return base.Channel.GetTCMSubscriber(loginToken, subscriberAddress);
        }
        
        public System.Threading.Tasks.Task<Common.TerminatingCallManagementV3.TCMType> GetTCMSubscriberAsync(string loginToken, string subscriberAddress) {
            return base.Channel.GetTCMSubscriberAsync(loginToken, subscriberAddress);
        }
        
        public void AddTCMSubscriber(string loginToken, string subscriberAddress, bool tcmEnabled, bool dndEnabled, Common.TerminatingCallManagementV3.SubscriberType subscriber) {
            base.Channel.AddTCMSubscriber(loginToken, subscriberAddress, tcmEnabled, dndEnabled, subscriber);
        }
        
        public System.Threading.Tasks.Task AddTCMSubscriberAsync(string loginToken, string subscriberAddress, bool tcmEnabled, bool dndEnabled, Common.TerminatingCallManagementV3.SubscriberType subscriber) {
            return base.Channel.AddTCMSubscriberAsync(loginToken, subscriberAddress, tcmEnabled, dndEnabled, subscriber);
        }
        
        public void UpdateTCMSubscriber(string loginToken, Common.TerminatingCallManagementV3.TCMType tcmSub, Common.TerminatingCallManagementV3.InternetAccessType internetInfo) {
            base.Channel.UpdateTCMSubscriber(loginToken, tcmSub, internetInfo);
        }
        
        public System.Threading.Tasks.Task UpdateTCMSubscriberAsync(string loginToken, Common.TerminatingCallManagementV3.TCMType tcmSub, Common.TerminatingCallManagementV3.InternetAccessType internetInfo) {
            return base.Channel.UpdateTCMSubscriberAsync(loginToken, tcmSub, internetInfo);
        }
        
        public void DeleteTCMSubscriber(string loginToken, string subscriberAddress) {
            base.Channel.DeleteTCMSubscriber(loginToken, subscriberAddress);
        }
        
        public System.Threading.Tasks.Task DeleteTCMSubscriberAsync(string loginToken, string subscriberAddress) {
            return base.Channel.DeleteTCMSubscriberAsync(loginToken, subscriberAddress);
        }
        
        public void TCMFeature(string loginToken, string subscriberAddress, bool enabled) {
            base.Channel.TCMFeature(loginToken, subscriberAddress, enabled);
        }
        
        public System.Threading.Tasks.Task TCMFeatureAsync(string loginToken, string subscriberAddress, bool enabled) {
            return base.Channel.TCMFeatureAsync(loginToken, subscriberAddress, enabled);
        }
        
        public void DNDFeature(string loginToken, string subscriberAddress, bool enabled) {
            base.Channel.DNDFeature(loginToken, subscriberAddress, enabled);
        }
        
        public System.Threading.Tasks.Task DNDFeatureAsync(string loginToken, string subscriberAddress, bool enabled) {
            return base.Channel.DNDFeatureAsync(loginToken, subscriberAddress, enabled);
        }
        
        public Common.TerminatingCallManagementV3.DNDContactListType[] GetSubscribersContacts(string loginToken, string subscriberAddress) {
            return base.Channel.GetSubscribersContacts(loginToken, subscriberAddress);
        }
        
        public System.Threading.Tasks.Task<Common.TerminatingCallManagementV3.DNDContactListType[]> GetSubscribersContactsAsync(string loginToken, string subscriberAddress) {
            return base.Channel.GetSubscribersContactsAsync(loginToken, subscriberAddress);
        }
    }
}
