using System;
using Common.Lib.Mapping;

namespace ANDP.Provisioning.API.Rest.Models.ApMax.MappingProfiles
{
    public class IptvAccountTypeProfile : CommonMappingProfile
    {
        protected override void Configure()
        {
            CreateMap<IptvAccountType, Common.IPTVServiceV3.IPTVAccountType>()
                .ForMember(dest => dest.ExtensionData, opt => opt.Ignore())
                .ForMember(dest => dest.AccountDescription, opt => opt.MapFrom(src => src.AccountDescription))
                .ForMember(dest => dest.Active, opt => opt.MapFrom(src => src.Active))
                .ForMember(dest => dest.AdultChannelsActive, opt => opt.MapFrom(src => src.AdultChannelsState))
                .ForMember(dest => dest.BillingServiceID, opt => opt.Ignore())
                .ForMember(dest => dest.ChannelPackageList, opt => opt.MapFrom(src => src.ChannelPackageTypes))
                .ForMember(dest => dest.CurrentAmountCharged, opt => opt.MapFrom(src => src.CurrentAmountCharged))
                .ForMember(dest => dest.DeactivateReason, opt => opt.MapFrom(src => src.DeactivateReason))
                .ForMember(dest => dest.DefaultMiddlewareType, opt => opt.Ignore())
                .ForMember(dest => dest.FIPSCountyCode, opt => opt.MapFrom(src => src.FipsCountyCode))
                .ForMember(dest => dest.FIPSStateCode, opt => opt.MapFrom(src => src.FipsStateCode))
                .ForMember(dest => dest.HideAdultChannels, opt => opt.Ignore())
                .ForMember(dest => dest.MaxBandwidthKbps, opt => opt.MapFrom(src => src.MaxBandwidthKbs))
                .ForMember(dest => dest.MaxChargingLimit, opt => opt.MapFrom(src => src.MaxChargingLimit))
                .ForMember(dest => dest.NextMonthAmountCharged, opt => opt.Ignore())
                .ForMember(dest => dest.PurchasePIN, opt => opt.MapFrom(src => src.PurchasePin.ToString()))
                .ForMember(dest => dest.RatingPIN, opt => opt.MapFrom(src => src.RatingPin.ToString()))
                .ForMember(dest => dest.ServeFeaturesList, opt => opt.Ignore())
                .ForMember(dest => dest.ServiceAreaID, opt => opt.MapFrom(src => src.ServiceAreaId))
                .ForMember(dest => dest.ServiceReference, opt => opt.MapFrom(src => src.ServiceReference))
                .ForMember(dest => dest.SetTopBoxList, opt => opt.MapFrom(src => src.SetTopBoxTypes))
                .ForMember(dest => dest.SubscriberID, opt => opt.MapFrom(src => src.SubscriberId))
                .ForMember(dest => dest.SubscriberName, opt => opt.MapFrom(src => src.SubscriberName))
                .ForMember(dest => dest.Comment, opt => opt.MapFrom(src => src.Comment))
                .ForMember(dest => dest.MaxAllowedStbs, opt => opt.MapFrom(src => src.MaxAllowedStbs))
                .ForMember(dest => dest.RoutePort, opt => opt.MapFrom(src => src.RoutePort))
                ;

            CreateMap<IptvAccountType, Common.IPTVServiceV7.IPTVAccountType>()
                .ForMember(dest => dest.ExtensionData, opt => opt.Ignore())
                .ForMember(dest => dest.AccountDescription, opt => opt.MapFrom(src => src.AccountDescription))
                .ForMember(dest => dest.Active, opt => opt.MapFrom(src => src.Active))
                .ForMember(dest => dest.AdultChannelsActive, opt => opt.MapFrom(src => src.AdultChannelsState))
                .ForMember(dest => dest.BillingServiceID, opt => opt.Ignore())
                .ForMember(dest => dest.ChannelPackageList, opt => opt.MapFrom(src => src.ChannelPackageTypes))
                .ForMember(dest => dest.CurrentAmountCharged, opt => opt.MapFrom(src => src.CurrentAmountCharged))
                .ForMember(dest => dest.DeactivateReason, opt => opt.MapFrom(src => src.DeactivateReason))
                .ForMember(dest => dest.DefaultMiddlewareType, opt => opt.Ignore())
                .ForMember(dest => dest.FIPSCountyCode, opt => opt.MapFrom(src => src.FipsCountyCode))
                .ForMember(dest => dest.FIPSStateCode, opt => opt.MapFrom(src => src.FipsStateCode))
                .ForMember(dest => dest.HideAdultChannels, opt => opt.Ignore())
                .ForMember(dest => dest.MaxBandwidthKbps, opt => opt.MapFrom(src => src.MaxBandwidthKbs))
                .ForMember(dest => dest.MaxChargingLimit, opt => opt.MapFrom(src => src.MaxChargingLimit))
                .ForMember(dest => dest.NextMonthAmountCharged, opt => opt.Ignore())
                .ForMember(dest => dest.PurchasePIN, opt => opt.MapFrom(src => src.PurchasePin))
                .ForMember(dest => dest.RatingPIN, opt => opt.MapFrom(src => src.RatingPin))
                .ForMember(dest => dest.ServeFeaturesList, opt => opt.Ignore())
                .ForMember(dest => dest.ServiceAreaID, opt => opt.MapFrom(src => src.ServiceAreaId))
                .ForMember(dest => dest.ServiceReference, opt => opt.MapFrom(src => src.ServiceReference))
                .ForMember(dest => dest.SetTopBoxList, opt => opt.MapFrom(src => src.SetTopBoxTypes))
                .ForMember(dest => dest.SubscriberID, opt => opt.MapFrom(src => src.SubscriberId))
                .ForMember(dest => dest.SubscriberName, opt => opt.MapFrom(src => src.SubscriberName))
                .ForMember(dest => dest.Comment, opt => opt.MapFrom(src => src.Comment))
                .ForMember(dest => dest.MaxAllowedStbs, opt => opt.MapFrom(src => src.MaxAllowedStbs))
                .ForMember(dest => dest.RoutePort, opt => opt.MapFrom(src => src.RoutePort))
                ;

            CreateMap<Common.IPTVServiceV3.IPTVAccountType, IptvAccountType>()
                .ForMember(dest => dest.AccountDescription, opt => opt.MapFrom(src => src.AccountDescription))
                .ForMember(dest => dest.Active, opt => opt.MapFrom(src => src.Active))
                .ForMember(dest => dest.AdultChannelsState, opt => opt.MapFrom(src => src.AdultChannelsActive))
                .ForMember(dest => dest.CurrentAmountCharged, opt => opt.MapFrom(src => src.CurrentAmountCharged))
                .ForMember(dest => dest.DeactivateReason, opt => opt.MapFrom(src => src.DeactivateReason))
                .ForMember(dest => dest.MaxChargingLimit, opt => opt.MapFrom(src => src.MaxChargingLimit))
                .ForMember(dest => dest.ServiceReference, opt => opt.MapFrom(src => src.ServiceReference))
                .ForMember(dest => dest.SubscriberName, opt => opt.MapFrom(src => src.SubscriberName))
                .ForMember(dest => dest.ChannelPackageTypes, opt => opt.MapFrom(src => src.ChannelPackageList))
                .ForMember(dest => dest.MaxBandwidthKbs, opt => opt.MapFrom(src => src.MaxBandwidthKbps))
                .ForMember(dest => dest.PurchasePin, opt => opt.MapFrom(src => src.PurchasePIN))
                .ForMember(dest => dest.RatingPin, opt => opt.MapFrom(src => src.RatingPIN))
                .ForMember(dest => dest.SetTopBoxTypes, opt => opt.MapFrom(src => src.SetTopBoxList))
                ;

            CreateMap<Common.IPTVServiceV7.IPTVAccountType, IptvAccountType>()
                .ForMember(dest => dest.AccountDescription, opt => opt.MapFrom(src => src.AccountDescription))
                .ForMember(dest => dest.Active, opt => opt.MapFrom(src => src.Active))
                .ForMember(dest => dest.AdultChannelsState, opt => opt.MapFrom(src => src.AdultChannelsActive))
                .ForMember(dest => dest.CurrentAmountCharged, opt => opt.MapFrom(src => src.CurrentAmountCharged))
                .ForMember(dest => dest.DeactivateReason, opt => opt.MapFrom(src => src.DeactivateReason))
                .ForMember(dest => dest.MaxChargingLimit, opt => opt.MapFrom(src => src.MaxChargingLimit))
                .ForMember(dest => dest.ServiceReference, opt => opt.MapFrom(src => src.ServiceReference))
                .ForMember(dest => dest.SubscriberName, opt => opt.MapFrom(src => src.SubscriberName))
                .ForMember(dest => dest.ChannelPackageTypes, opt => opt.MapFrom(src => src.ChannelPackageList))
                .ForMember(dest => dest.MaxBandwidthKbs, opt => opt.MapFrom(src => src.MaxBandwidthKbps))
                .ForMember(dest => dest.PurchasePin, opt => opt.MapFrom(src => src.PurchasePIN))
                .ForMember(dest => dest.RatingPin, opt => opt.MapFrom(src => src.RatingPIN))
                .ForMember(dest => dest.SetTopBoxTypes, opt => opt.MapFrom(src => src.SetTopBoxList))
                ;
        }
    }
}