using Common.Lib.Mapping;

namespace ANDP.Provisioning.API.Rest.Models.ApMax.MappingProfiles
{
    public class PackageTypeProfile : CommonMappingProfile
    {
        protected override void Configure()
        {
            CreateMap<PackageType, Common.VoicemailV3.PackageType>()
                .ForMember(dest => dest.ExtensionData, opt => opt.Ignore())
                .ForMember(dest => dest.AdminEntryPointField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowBroadcastMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowDailyScheduleField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowEmailDeletionField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowForwardingMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowFutureDeliveryField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowHolidayScheduleField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowInitialActionsField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowOutdialField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowOutdialListEditField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowPagerNotificationField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowRecordingField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowSendingMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowSpecificCallerField, opt => opt.Ignore())
                //.ForMember(dest => dest.AllowTemporaryGreetingsField, opt => opt.Ignore())
                //.ForMember(dest => dest.AppleVisualVoicemail, opt => opt.Ignore())
                .ForMember(dest => dest.AutoForwardMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.AutoForwardToAddressField, opt => opt.Ignore())
                .ForMember(dest => dest.CallScreeningField, opt => opt.Ignore())
                .ForMember(dest => dest.CallingPartyField, opt => opt.Ignore())
                //.ForMember(dest => dest.ContinuousPlaybackField, opt => opt.Ignore())
                .ForMember(dest => dest.DailyNotificationStatusField, opt => opt.Ignore())
                .ForMember(dest => dest.DailyNotificationTimeField, opt => opt.Ignore())
                .ForMember(dest => dest.DeleteShortKnownMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.DeleteShortUnknownMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.DescriptionField, opt => opt.MapFrom(src => src.Description))
                //.ForMember(dest => dest.EmailNotificationDisabledField, opt => opt.Ignore())
                .ForMember(dest => dest.EmailOnlyField, opt => opt.Ignore())
                .ForMember(dest => dest.EmailcodecTypeField, opt => opt.Ignore())
                .ForMember(dest => dest.ForceLanguageChoiceField, opt => opt.Ignore())
                .ForMember(dest => dest.ForcePasswordChangeField, opt => opt.Ignore())
                .ForMember(dest => dest.GreetingInterruptDigitField, opt => opt.Ignore())
                .ForMember(dest => dest.GuidField, opt => opt.Ignore())
                .ForMember(dest => dest.InterPageDelayField, opt => opt.Ignore())
                .ForMember(dest => dest.LanguageField, opt => opt.Ignore())
                .ForMember(dest => dest.LoginTypeField, opt => opt.Ignore())
                .ForMember(dest => dest.MaxDistributionListsField, opt => opt.Ignore())
                .ForMember(dest => dest.MaxMessageLengthField, opt => opt.Ignore())
                .ForMember(dest => dest.MaxMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.MaxRecordTimeField, opt => opt.Ignore())
                //.ForMember(dest => dest.MaxRegisteredDevicesField, opt => opt.Ignore())
                .ForMember(dest => dest.MaxSubmailboxesField, opt => opt.Ignore())
                .ForMember(dest => dest.MessagePlaybackOrderField, opt => opt.Ignore())
                //.ForMember(dest => dest.MinimumPasswordLengthField, opt => opt.Ignore())
                .ForMember(dest => dest.NewMessageRetentionField, opt => opt.Ignore())
                //.ForMember(dest => dest.NewMessageSortOrderField, opt => opt.Ignore())
                .ForMember(dest => dest.PageUrgentOnlyField, opt => opt.Ignore())
                .ForMember(dest => dest.PagerAttemptsField, opt => opt.Ignore())
                .ForMember(dest => dest.PasswordField, opt => opt.Ignore())
                .ForMember(dest => dest.PlayAfterPromptField, opt => opt.Ignore())
                .ForMember(dest => dest.PlayBusyGreetingField, opt => opt.Ignore())
                //.ForMember(dest => dest.PlayEndOfMessageOptionField, opt => opt.Ignore())
                .ForMember(dest => dest.PrePageDelayField, opt => opt.Ignore())
                .ForMember(dest => dest.ReplyTypeField, opt => opt.Ignore())
                .ForMember(dest => dest.SavedMessageRetentionField, opt => opt.Ignore())
                //.ForMember(dest => dest.SavedMessageSortOrderField, opt => opt.Ignore())
                .ForMember(dest => dest.ShortMessageCriteriaField, opt => opt.Ignore())
                //.ForMember(dest => dest.SingleGreetingMenusField, opt => opt.Ignore())
                .ForMember(dest => dest.VideoMWIUpdateRateField, opt => opt.Ignore())
                //.ForMember(dest => dest.VoiceTranscriptionField, opt => opt.Ignore())
                 ;

            CreateMap<PackageType, Common.VoicemailV4.PackageType>()
                .ForMember(dest => dest.ExtensionData, opt => opt.Ignore())
                .ForMember(dest => dest.AdminEntryPointField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowBroadcastMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowDailyScheduleField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowEmailDeletionField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowForwardingMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowFutureDeliveryField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowHolidayScheduleField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowInitialActionsField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowOutdialField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowOutdialListEditField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowPagerNotificationField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowRecordingField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowSendingMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowSpecificCallerField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowTemporaryGreetingsField, opt => opt.Ignore())
                //.ForMember(dest => dest.AppleVisualVoicemail, opt => opt.Ignore())
                .ForMember(dest => dest.AutoForwardMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.AutoForwardToAddressField, opt => opt.Ignore())
                .ForMember(dest => dest.CallScreeningField, opt => opt.Ignore())
                .ForMember(dest => dest.CallingPartyField, opt => opt.Ignore())
                .ForMember(dest => dest.ContinuousPlaybackField, opt => opt.Ignore())
                .ForMember(dest => dest.DailyNotificationStatusField, opt => opt.Ignore())
                .ForMember(dest => dest.DailyNotificationTimeField, opt => opt.Ignore())
                .ForMember(dest => dest.DeleteShortKnownMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.DeleteShortUnknownMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.DescriptionField, opt => opt.MapFrom(src => src.Description))
                //.ForMember(dest => dest.EmailNotificationDisabledField, opt => opt.Ignore())
                .ForMember(dest => dest.EmailOnlyField, opt => opt.Ignore())
                .ForMember(dest => dest.EmailcodecTypeField, opt => opt.Ignore())
                .ForMember(dest => dest.ForceLanguageChoiceField, opt => opt.Ignore())
                .ForMember(dest => dest.ForcePasswordChangeField, opt => opt.Ignore())
                .ForMember(dest => dest.GreetingInterruptDigitField, opt => opt.Ignore())
                .ForMember(dest => dest.GuidField, opt => opt.Ignore())
                .ForMember(dest => dest.InterPageDelayField, opt => opt.Ignore())
                .ForMember(dest => dest.LanguageField, opt => opt.Ignore())
                .ForMember(dest => dest.LoginTypeField, opt => opt.Ignore())
                .ForMember(dest => dest.MaxDistributionListsField, opt => opt.Ignore())
                .ForMember(dest => dest.MaxMessageLengthField, opt => opt.Ignore())
                .ForMember(dest => dest.MaxMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.MaxRecordTimeField, opt => opt.Ignore())
                //.ForMember(dest => dest.MaxRegisteredDevicesField, opt => opt.Ignore())
                .ForMember(dest => dest.MaxSubmailboxesField, opt => opt.Ignore())
                .ForMember(dest => dest.MessagePlaybackOrderField, opt => opt.Ignore())
                //.ForMember(dest => dest.MinimumPasswordLengthField, opt => opt.Ignore())
                .ForMember(dest => dest.NewMessageRetentionField, opt => opt.Ignore())
                //.ForMember(dest => dest.NewMessageSortOrderField, opt => opt.Ignore())
                .ForMember(dest => dest.PageUrgentOnlyField, opt => opt.Ignore())
                .ForMember(dest => dest.PagerAttemptsField, opt => opt.Ignore())
                .ForMember(dest => dest.PasswordField, opt => opt.Ignore())
                .ForMember(dest => dest.PlayAfterPromptField, opt => opt.Ignore())
                .ForMember(dest => dest.PlayBusyGreetingField, opt => opt.Ignore())
                .ForMember(dest => dest.PlayEndOfMessageOptionField, opt => opt.Ignore())
                .ForMember(dest => dest.PrePageDelayField, opt => opt.Ignore())
                .ForMember(dest => dest.ReplyTypeField, opt => opt.Ignore())
                .ForMember(dest => dest.SavedMessageRetentionField, opt => opt.Ignore())
                //.ForMember(dest => dest.SavedMessageSortOrderField, opt => opt.Ignore())
                .ForMember(dest => dest.ShortMessageCriteriaField, opt => opt.Ignore())
                //.ForMember(dest => dest.SingleGreetingMenusField, opt => opt.Ignore())
                .ForMember(dest => dest.VideoMWIUpdateRateField, opt => opt.Ignore())
                //.ForMember(dest => dest.VoiceTranscriptionField, opt => opt.Ignore())
                 ;

            CreateMap<PackageType, Common.VoicemailV5.PackageType>()
                .ForMember(dest => dest.ExtensionData, opt => opt.Ignore())
                .ForMember(dest => dest.AdminEntryPointField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowBroadcastMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowDailyScheduleField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowEmailDeletionField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowForwardingMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowFutureDeliveryField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowHolidayScheduleField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowInitialActionsField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowOutdialField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowOutdialListEditField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowPagerNotificationField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowRecordingField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowSendingMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowSpecificCallerField, opt => opt.Ignore())
                .ForMember(dest => dest.AllowTemporaryGreetingsField, opt => opt.Ignore())
                .ForMember(dest => dest.AppleVisualVoicemail, opt => opt.Ignore())
                .ForMember(dest => dest.AutoForwardMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.AutoForwardToAddressField, opt => opt.Ignore())
                .ForMember(dest => dest.CallScreeningField, opt => opt.Ignore())
                .ForMember(dest => dest.CallingPartyField, opt => opt.Ignore())
                .ForMember(dest => dest.ContinuousPlaybackField, opt => opt.Ignore())
                .ForMember(dest => dest.DailyNotificationStatusField, opt => opt.Ignore())
                .ForMember(dest => dest.DailyNotificationTimeField, opt => opt.Ignore())
                .ForMember(dest => dest.DeleteShortKnownMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.DeleteShortUnknownMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.DescriptionField, opt => opt.MapFrom(src => src.Description))
                .ForMember(dest => dest.EmailNotificationDisabledField, opt => opt.Ignore())
                .ForMember(dest => dest.EmailOnlyField, opt => opt.Ignore())
                .ForMember(dest => dest.EmailcodecTypeField, opt => opt.Ignore())
                .ForMember(dest => dest.ForceLanguageChoiceField, opt => opt.Ignore())
                .ForMember(dest => dest.ForcePasswordChangeField, opt => opt.Ignore())
                .ForMember(dest => dest.GreetingInterruptDigitField, opt => opt.Ignore())
                .ForMember(dest => dest.GuidField, opt => opt.Ignore())
                .ForMember(dest => dest.InterPageDelayField, opt => opt.Ignore())
                .ForMember(dest => dest.LanguageField, opt => opt.Ignore())
                .ForMember(dest => dest.LoginTypeField, opt => opt.Ignore())
                .ForMember(dest => dest.MaxDistributionListsField, opt => opt.Ignore())
                .ForMember(dest => dest.MaxMessageLengthField, opt => opt.Ignore())
                .ForMember(dest => dest.MaxMessagesField, opt => opt.Ignore())
                .ForMember(dest => dest.MaxRecordTimeField, opt => opt.Ignore())
                .ForMember(dest => dest.MaxRegisteredDevicesField, opt => opt.Ignore())
                .ForMember(dest => dest.MaxSubmailboxesField, opt => opt.Ignore())
                .ForMember(dest => dest.MessagePlaybackOrderField, opt => opt.Ignore())
                .ForMember(dest => dest.MinimumPasswordLengthField, opt => opt.Ignore())
                .ForMember(dest => dest.NewMessageRetentionField, opt => opt.Ignore())
                .ForMember(dest => dest.NewMessageSortOrderField, opt => opt.Ignore())
                .ForMember(dest => dest.PageUrgentOnlyField, opt => opt.Ignore())
                .ForMember(dest => dest.PagerAttemptsField, opt => opt.Ignore())
                .ForMember(dest => dest.PasswordField, opt => opt.Ignore())
                .ForMember(dest => dest.PlayAfterPromptField, opt => opt.Ignore())
                .ForMember(dest => dest.PlayBusyGreetingField, opt => opt.Ignore())
                .ForMember(dest => dest.PlayEndOfMessageOptionField, opt => opt.Ignore())
                .ForMember(dest => dest.PrePageDelayField, opt => opt.Ignore())
                .ForMember(dest => dest.ReplyTypeField, opt => opt.Ignore())
                .ForMember(dest => dest.SavedMessageRetentionField, opt => opt.Ignore())
                .ForMember(dest => dest.SavedMessageSortOrderField, opt => opt.Ignore())
                .ForMember(dest => dest.ShortMessageCriteriaField, opt => opt.Ignore())
                .ForMember(dest => dest.SingleGreetingMenusField, opt => opt.Ignore())
                .ForMember(dest => dest.VideoMWIUpdateRateField, opt => opt.Ignore())
                .ForMember(dest => dest.VoiceTranscriptionField, opt => opt.Ignore())
                 ;

            CreateMap<Common.VoicemailV3.PackageType, PackageType>()
                .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.DescriptionField))
                ;

            CreateMap<Common.VoicemailV4.PackageType, PackageType>()
                .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.DescriptionField))
                ;

            CreateMap<Common.VoicemailV5.PackageType, PackageType>()
                .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.DescriptionField))
                ;
        }
    }
}